/** Export-dir README.md renderer (_write_readme in the Python, verbatim). */
import type { Summary } from "./summary";

export function renderReadme(S: Summary): string {
  const rc = {
    problems: S.problems.length,
    allergies: S.allergies.length,
    immunizations: S.immunizations.length,
    medications: S.medications.length,
    results: S.test_results.length,
    encounters: S.encounters.length,
    threads: S.messages.threads,
    messages: S.messages.total_messages,
  };
  const L: string[] = [
    "# MyChart Personal Health Record — Export",
    "",
    `Generated **${S.generated}** from **${S.source}** by \`export.py\` (deterministic; no LLM in the loop).`,
    "",
    "**Start with `PATIENT_SUMMARY.md`** (human-readable) and `indexes/*.csv` (spreadsheets).",
    "",
    "## Counts",
    `- Problems: ${rc.problems} · Allergies: ${rc.allergies} · Immunizations: ${rc.immunizations} · Medications: ${rc.medications}`,
    `- Test/imaging result orders: ${rc.results} (components in \`indexes/test_result_components.csv\`)`,
    `- Encounters: ${rc.encounters} (After-Visit Summaries in \`structured/visits/avs/\`, notes in \`structured/visits/notes/\`)`,
    `- Message threads: ${rc.threads} / ${rc.messages} messages (\`structured/messages/threads_full/\`)`,
    "",
    "## Layout",
    "```",
    "PATIENT_SUMMARY.md / .json   consolidated summary",
    "indexes/*.csv                flat spreadsheets",
    "MANIFEST.json                file + record counts",
    "structured/                  structured JSON per domain (source of truth)",
    "  test-results/details/        per-order values, ranges, narratives",
    "  visits/avs|notes/            After-Visit Summaries + clinical notes (HTML)",
    "  messages/threads_full/       per-thread JSON + per-message HTML bodies",
    "  _captured_from_navigation/   best JSON body per endpoint (provenance)",
    "raw_network/                 raw response log + bodies (only if raw capture on)",
    "documents/ccda/              standards C-CDA export (only if --ccda)",
    "  HealthSummary_all_visits_CCDA.zip   IHE-XDM package",
    "  extracted/                          unpacked C-CDA XML docs (one per visit)",
    "```",
    "",
    "## How the data is obtained",
    "MyChart's web app POSTs to `/MyChart/api/<area>/<Method>` (JSON) with an",
    "`__RequestVerificationToken` header fetched from `/MyChart/Home/CSRFToken`.",
    "`export.py` replays those calls from inside the authenticated page (real cookies",
    "+ headers), paginates lists, and fetches per-item detail (result `GetDetails`",
    "keyed by `eorderid`; AVS/notes via `report-content/LoadReportContent`; message",
    "threads via `conversations/GetConversationDetails`). File names are derived",
    "deterministically from API fields (e.g. a thread's `subject`).",
    "",
    "## Standards C-CDA (with `--ccda`)",
    "`documents/ccda/` holds the official **\"All visit records\"** export — an IHE-XDM",
    "ZIP of C-CDA documents (one `<ClinicalDocument>` per visit plus a health",
    "summary), unpacked under `extracted/`. This is an asynchronous server-side",
    "generation: the exporter requests it (`record-download/GetDownloadStarted`,",
    "mode `allVisits`), polls the Requested-Records list until ready, then downloads",
    "the bytes from `/Documents/Released/Download`. This is the standards-format",
    "counterpart to the JSON in `structured/`.",
    "",
    "## Not available session-only",
    "- **FHIR R4** — most Epic sites expose a FHIR API on a separate OAuth2 surface",
    "  that needs a registered `client_id`; MyChart cookies don't authenticate it.",
    "  The internal API above already yields the same clinical facts; the C-CDA above",
    "  is the standards-format export.",
    "- **EHI computer-readable export** — instance-dependent; where offered it is the",
    "  deepest export tier (some instances disable it and redirect to Home).",
    "",
    "This directory contains PHI. It is stored locally and was not published anywhere.",
  ];
  return L.join("\n") + "\n";
}
